// Generated by https://quicktype.io

export interface ShellyScripts {
    scripts: Script[];
}

export interface Script {
    id:      number;
    name:    string;
    enable:  boolean;
    running: boolean;
}
