// Generated by https://quicktype.io
export var MqttFingerprint1;
(function (MqttFingerprint1) {
    MqttFingerprint1["The0X00"] = "0x00";
    MqttFingerprint1["The0X01"] = "0x01";
    MqttFingerprint1["The0X03"] = "0x03";
    MqttFingerprint1["The0X0E"] = "0x0e";
    MqttFingerprint1["The0X16"] = "0x16";
    MqttFingerprint1["The0X1A"] = "0x1a";
    MqttFingerprint1["The0X21"] = "0x21";
    MqttFingerprint1["The0X2E"] = "0x2e";
    MqttFingerprint1["The0X48"] = "0x48";
})(MqttFingerprint1 || (MqttFingerprint1 = {}));
export var Days;
(function (Days) {
    Days["The0B0000000"] = "0b0000000";
})(Days || (Days = {}));
export var Time;
(function (Time) {
    Time["The0X000"] = "0x000";
})(Time || (Time = {}));
//# sourceMappingURL=tasdefs.js.map